package com.humanize.contracts.events;

public enum EventType {
    USER_AUTHENTICATED,
    BOOK_UPLOADED,
    BOOK_PROCESSING_STARTED,
    BOOK_PROCESSING_COMPLETED,
    BOOK_PROCESSING_FAILED,
    BOOK_METADATA_EXTRACTED,
    READER_PROGRESS_UPDATED,
    READER_ACTIVITY_RECORDED,
    NOTIFICATION_SPOILER_REQUESTED,
    NOTIFICATION_SPOILER_GENERATED,
    NOTIFICATION_EMAIL_SENT,
    NOTIFICATION_EMAIL_FAILED
}
